(ns diplomacy.rulebook-sample-game
  (:require [diplomacy.datatypes :refer [create-order]]))

(defn- create-orders [orders]
  (map #(apply create-order %) orders))

;; this contains a good amount of supports, but only one convoy, and almost no
;; use of coasts. Be sure to add your own test cases to cover those!
(def rulebook-sample-game-turns
  {
   {:year 1901 :season :spring}
   (create-orders
    [[:austria :army :vie :attack :tri]
     [:austria :army :bud :attack :gal]
     [:austria :fleet :tri :attack :alb]
     [:england :army :lvp :attack :yor]
     [:england :fleet :lon :attack :nth]
     [:england :fleet :edi :attack :nrg]
     [:france :army :par :attack :bur]
     [:france :army :mar :attack :spa]
     [:france :fleet :bre :attack :pic]
     [:germany :army :ber :attack :kie]
     [:germany :army :mun :attack :ruh]
     [:germany :fleet :kie :attack :den]
     [:italy :army :ven :attack :pie]
     [:italy :army :rom :attack :ven]
     [:italy :fleet :nap :attack :ion]
     [:russia :army :mos :attack :ukr]
     [:russia :army :war :attack :gal]
     [:russia :fleet :stp-sc :attack :bot]
     [:russia :fleet :sev :attack :bla]
     [:turkey :army :con :attack :bul]
     [:turkey :army :smy :attack :con]
     [:turkey :fleet :ank :attack :bla]])
   {:year 1901 :season :fall}
   (create-orders
    [[:austria :army :tri :hold]
     [:austria :army :bud :attack :ser]
     [:austria :fleet :alb :attack :gre]
     [:england :army :yor :attack :nwy]
     [:england :fleet :nth :convoy :england :army :yor :attack :nwy]
     [:england :fleet :nrg :attack :bar]
     [:france :army :bur :attack :mar]
     [:france :army :spa :attack :por]
     [:france :fleet :pic :attack :bel]
     [:germany :army :kie :attack :hol]
     [:germany :army :ruh :attack :bel]
     [:germany :fleet :den :hold]
     [:italy :army :ven :hold]
     [:italy :army :pie :attack :mar]
     [:italy :fleet :ion :attack :tun]
     [:russia :army :ukr :support :russia :fleet :sev :attack :rum]
     [:russia :army :war :attack :gal]
     [:russia :fleet :bot :attack :swe]
     [:russia :fleet :sev :attack :rum]
     [:turkey :army :bul :attack :ser]
     [:turkey :army :con :attack :bul]
     [:turkey :fleet :ank :attack :bla]])
   {:year 1902 :season :spring}
   (create-orders
    [[:austria :army :tri :attack :bud]
     [:austria :army :vie :attack :bud]
     [:austria :army :bud :attack :ser]
     [:austria :fleet :gre :hold]
     [:england :army :nwy :attack :stp]
     [:england :fleet :nth :attack :nwy]
     [:england :fleet :bar :support :england :army :nwy :attack :stp]
     [:england :fleet :edi :attack :nth]
     [:france :army :bur :support :france :fleet :pic :attack :bel]
     [:france :army :por :attack :spa]
     [:france :fleet :pic :attack :bel]
     [:france :fleet :mar :hold]
     [:germany :army :hol :attack :bel]
     [:germany :army :ruh :support :germany :army :hol :attack :bel]
     [:germany :army :mun :attack :bur]
     [:germany :fleet :den :hold]
     [:germany :fleet :kie :attack :hol]
     [:italy :army :ven :hold]
     [:italy :army :pie :attack :mar]
     [:italy :fleet :tun :attack :wes]
     [:italy :fleet :nap :attack :tyn]
     [:russia :army :ukr :support :russia :fleet :rum :hold]
     [:russia :army :gal :attack :bud]
     [:russia :army :stp :attack :nwy]
     [:russia :army :sev :support :russia :fleet :rum :hold]
     [:russia :fleet :swe :support :russia :army :stp :attack :nwy]
     [:russia :fleet :rum :hold]
     [:turkey :army :bul :attack :rum]
     [:turkey :army :con :attack :bul]
     [:turkey :army :smy :attack :arm]
     [:turkey :fleet :bla :support :turkey :army :bul :attack :rum]])
   {:year 1902 :season :fall}
   (create-orders
    [[:austria :army :vie :attack :gal]
     [:austria :army :tri :attack :bud]
     [:austria :army :ser :support :turkey :army :bul :attack :rum]
     [:austria :fleet :gre :hold]
     [:england :army :nwy :attack :stp]
     [:england :fleet :bar :support :england :army :nwy :attack :stp]
     [:england :fleet :nth :attack :nwy]
     [:england :fleet :edi :attack :nth]
     [:france :army :bur :attack :bel]
     [:france :fleet :pic :support :france :army :bur :attack :bel]
     [:france :army :spa :support :france :fleet :mar :hold]
     [:france :fleet :mar :support :france :army :spa :hold]
     [:germany :army :ruh :attack :bur]
     [:germany :army :mun :support :germany :army :ruh :attack :bur]
     [:germany :army :bel :support :germany :army :ruh :attack :bur]
     [:germany :fleet :den :attack :swe]
     [:germany :fleet :hol :support :germany :army :bel :hold]
     [:italy :army :ven :attack :pie]
     [:italy :army :pie :attack :mar]
     [:italy :fleet :wes :attack :naf]
     [:italy :fleet :tyn :attack :gol]
     [:russia :army :stp :attack :nwy]
     [:russia :fleet :swe :support :russia :army :stp :attack :nwy]
     [:russia :fleet :rum :support :russia :army :sev :hold]
     [:russia :army :sev :support :russia :fleet :rum :hold]
     [:russia :army :gal :support :russia :fleet :rum :hold]
     [:russia :army :ukr :support :russia :army :sev :hold]
     [:turkey :army :bul :attack :rum]
     [:turkey :army :con :attack :bul]
     [:turkey :army :arm :attack :sev]
     [:turkey :fleet :bla :support :turkey :army :bul :attack :rum]])
    })
